// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

public class Ball : MonoBehaviour
{
	public Pitcher Pitcher;

	private bool destroyMe = false;
	private bool beingThrown = false;

	void OnCollisionEnter (Collision collision)
	{
		if (Pitcher != null) {
			if (collision.gameObject.name == "Field") {
				Debug.Log("hit ground");
				this.Pitcher.CatchBall ();
			}
		}
	}

	public void CatchBall()
	{
		Debug.Log ("Catching Ball");
		this.beingThrown = false;
		rigidbody.velocity = Vector3.zero;
		transform.position = new Vector3 (0, 10, 5);
	}

	public void ThrowBall()
	{
		Debug.Log ("throwing ball");
		this.beingThrown = true;
	}

	void Update()
	{
		if (this.beingThrown) {
			Debug.Log (this.beingThrown);
			this.rigidbody.AddForce (Vector3.forward * -15);
		}
	}
}